# Data Feature Engineering and One Hot Encoding

## 1. Import Required Libraries
Import pandas for data manipulation.

In [9]:
import pandas as pd

## 2. Load Data
Load the Data_Altered dataset into a pandas DataFrame.

In [10]:
df = pd.read_csv('Data.csv')
df.head()

,Price,Square Area,Bedrooms,Bathrooms,Furnishing,school,hospital,shopping_mall,supermarket,church,...,Neighborhood_Libis,Neighborhood_Loyola Heights,Neighborhood_New Manila,Neighborhood_North Avenue Area,Neighborhood_Novaliches,Neighborhood_Santa Mesa,Neighborhood_Santa Mesa Heights,Neighborhood_Santolan,Neighborhood_Timog and South Triangle,occupancy
0,12000,25.0,0,1,Semi Furnished,1,1,1,1,1,...,0,1,0,0,0,0,0,0,0,0
1,58000,61.0,1,1,Fully Furnished,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,14000,25.0,1,1,Fully Furnished,1,1,1,1,1,...,0,0,0,0,1,0,0,0,0,1
3,22000,28.0,0,1,Fully Furnished,1,1,1,1,1,...,0,1,0,0,0,0,0,0,0,0
4,18000,30.0,2,1,Unfurnished,1,1,1,1,1,...,0,0,0,0,1,0,0,0,0,0

## 3. One-Hot Encode Furnishing Column
Convert the 'Furnishing' column into three separate columns: 'Fully Furnished', 'Semi Furnished', and 'Unfurnished', with 0 for False and 1 for True.

In [11]:
df['Fully Furnished'] = (df['Furnishing'] == 'Fully Furnished').astype(int)
df['Semi Furnished'] = (df['Furnishing'] == 'Semi Furnished').astype(int)
df['Unfurnished'] = (df['Furnishing'] == 'Unfurnished').astype(int)
df.head()

,Price,Square Area,Bedrooms,Bathrooms,Furnishing,school,hospital,shopping_mall,supermarket,church,...,Neighborhood_North Avenue Area,Neighborhood_Novaliches,Neighborhood_Santa Mesa,Neighborhood_Santa Mesa Heights,Neighborhood_Santolan,Neighborhood_Timog and South Triangle,occupancy,Fully Furnished,Semi Furnished,Unfurnished
0,12000,25.0,0,1,Semi Furnished,1,1,1,1,1,...,0,0,0,0,0,0,0,0,1,0
1,58000,61.0,1,1,Fully Furnished,1,1,1,1,1,...,0,0,0,0,0,0,0,1,0,0
2,14000,25.0,1,1,Fully Furnished,1,1,1,1,1,...,0,1,0,0,0,0,1,1,0,0
3,22000,28.0,0,1,Fully Furnished,1,1,1,1,1,...,0,0,0,0,0,0,0,1,0,0
4,18000,30.0,2,1,Unfurnished,1,1,1,1,1,...,0,1,0,0,0,0,0,0,0,1

In [12]:
# Drop Furnishing column since it was already one hot encoded
df = df.drop(columns=['Furnishing'])

## 4. Calculate Price per Square Area
Create a new column 'price_per_sqm' by dividing the 'Price' column by the 'Square Area' column.

In [13]:
df['price_per_sqm'] = df['Price'] / df['Square Area']
df.head()

,Price,Square Area,Bedrooms,Bathrooms,school,hospital,shopping_mall,supermarket,church,park,...,Neighborhood_Novaliches,Neighborhood_Santa Mesa,Neighborhood_Santa Mesa Heights,Neighborhood_Santolan,Neighborhood_Timog and South Triangle,occupancy,Fully Furnished,Semi Furnished,Unfurnished,price_per_sqm
0,12000,25.0,0,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,1,0,480.000000
1,58000,61.0,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,1,0,0,950.819672
2,14000,25.0,1,1,1,1,1,1,1,1,...,1,0,0,0,0,1,1,0,0,560.000000
3,22000,28.0,0,1,1,1,1,1,1,1,...,0,0,0,0,0,0,1,0,0,785.714286
4,18000,30.0,2,1,1,1,1,1,1,1,...,1,0,0,0,0,0,0,0,1,600.000000

## 5. Create Price per Square Meter x Bedrooms Column
Create a new column 'price_per_sqm_x_bedrooms' by multiplying 'price_per_sqm' by the number of bedrooms.

In [14]:
df['price_per_sqm_x_bedrooms'] = df['price_per_sqm'] * df['Bedrooms']
df.head()

,Price,Square Area,Bedrooms,Bathrooms,school,hospital,shopping_mall,supermarket,church,park,...,Neighborhood_Santa Mesa,Neighborhood_Santa Mesa Heights,Neighborhood_Santolan,Neighborhood_Timog and South Triangle,occupancy,Fully Furnished,Semi Furnished,Unfurnished,price_per_sqm,price_per_sqm_x_bedrooms
0,12000,25.0,0,1,1,1,1,1,1,1,...,0,0,0,0,0,0,1,0,480.000000,0.000000
1,58000,61.0,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,950.819672,950.819672
2,14000,25.0,1,1,1,1,1,1,1,1,...,0,0,0,0,1,1,0,0,560.000000,560.000000
3,22000,28.0,0,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,785.714286,0.000000
4,18000,30.0,2,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,1,600.000000,1200.000000

## 6. Create Price per Square Meter x Bathrooms Column
Create a new column 'price_per_sqm_x_bathrooms' by multiplying 'price_per_sqm' by the number of bathrooms.

In [15]:
df['price_per_sqm_x_bathrooms'] = df['price_per_sqm'] * df['Bathrooms']
df.head()

,Price,Square Area,Bedrooms,Bathrooms,school,hospital,shopping_mall,supermarket,church,park,...,Neighborhood_Santa Mesa Heights,Neighborhood_Santolan,Neighborhood_Timog and South Triangle,occupancy,Fully Furnished,Semi Furnished,Unfurnished,price_per_sqm,price_per_sqm_x_bedrooms,price_per_sqm_x_bathrooms
0,12000,25.0,0,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,480.000000,0.000000,480.000000
1,58000,61.0,1,1,1,1,1,1,1,1,...,0,0,0,0,1,0,0,950.819672,950.819672,950.819672
2,14000,25.0,1,1,1,1,1,1,1,1,...,0,0,0,1,1,0,0,560.000000,560.000000,560.000000
3,22000,28.0,0,1,1,1,1,1,1,1,...,0,0,0,0,1,0,0,785.714286,0.000000,785.714286
4,18000,30.0,2,1,1,1,1,1,1,1,...,0,0,0,0,0,0,1,600.000000,1200.000000,600.000000

In [17]:
correlations = df.corr()['Price'].sort_values(ascending=False)
display(correlations)

Price                                    1.000000
Square Area                              0.798326
Bathrooms                                0.687436
price_per_sqm_x_bathrooms                0.677874
price_per_sqm_x_bedrooms                 0.663908
Bedrooms                                 0.639777
Parking                                  0.202756
Storage Space                            0.162074
Pets Allowed                             0.153451
Balcony                                  0.138291
Neighborhood_New Manila                  0.093098
Unfurnished                              0.068080
occupancy                                0.066718
Neighborhood_Diliman                     0.061428
Play Room                                0.057205
Neighborhood_Eastwood City               0.055319
Neighborhood_Santa Mesa                  0.046867
Neighborhood_Fairview                    0.044956
Neighborhood_Libis                       0.043127
price_per_sqm                            0.033751
Gym                                      0.022868
Neighborhood_Santa Mesa Heights          0.016238
shopping_mall                            0.009230
school                                  -0.000642
restaurant                              -0.002983
Semi Furnished                          -0.003284
church                                  -0.007106
Neighborhood_Circuit Makati             -0.008690
Multi-Purpose Hall                      -0.010347
gym                                     -0.013983
supermarket                             -0.017210
Study Hall                              -0.020367
Neighborhood_Loyola Heights             -0.028182
park                                    -0.030480
train_station                           -0.031983
bank                                    -0.037018
Jogging Trail                           -0.037536
bus_station                             -0.041822
hospital                                -0.046681
Neighborhood_Santolan                   -0.047850
Neighborhood_Commonwealth Area          -0.049177
Neighborhood_Araneta Center Cubao       -0.049622
Fully Furnished                         -0.050207
Neighborhood_Timog and South Triangle   -0.050924
Concierge                               -0.074498
Neighborhood_North Avenue Area          -0.075042
university                              -0.077013
police                                  -0.087447
pharmacy                                -0.089211
Function Rooms                          -0.089211
Neighborhood_Novaliches                 -0.093748
transit_station                         -0.096506
24/7 Security                           -0.138912
Swimming pool                           -0.158654
subway_station                                NaN
Name: Price, dtype: float64

In [20]:
# Define a correlation threshold
correlation_threshold = 0.1

# Get the absolute correlations with 'Price'
abs_correlations = df.corr()['Price'].abs()

# Identify columns to drop (excluding 'Price' itself and specific columns to keep/drop)
columns_to_drop = abs_correlations[abs_correlations < correlation_threshold].index.tolist()
if 'Price' in columns_to_drop:
    columns_to_drop.remove('Price')

# Explicitly remove 'subway_station' if it exists
if 'subway_station' in df.columns:
    columns_to_drop.append('subway_station')

# Explicitly keep 'price_per_sqm' if it was in the list to drop
if 'price_per_sqm' in columns_to_drop:
    columns_to_drop.remove('price_per_sqm')

# Drop the identified columns
df_reduced = df.drop(columns=columns_to_drop)

print(f"Dropped {len(columns_to_drop)} columns with absolute correlation less than {correlation_threshold} with 'Price' or explicitly requested to be dropped.")
display(df_reduced.head())

Dropped 42 columns with absolute correlation less than 0.1 with 'Price' or explicitly requested to be dropped.

,Price,Square Area,Bedrooms,Bathrooms,24/7 Security,Balcony,Parking,Pets Allowed,Storage Space,Swimming pool,price_per_sqm,price_per_sqm_x_bedrooms,price_per_sqm_x_bathrooms
0,12000,25.0,0,1,1,0,0,0,0,1,480.000000,0.000000,480.000000
1,58000,61.0,1,1,0,0,0,0,0,0,950.819672,950.819672,950.819672
2,14000,25.0,1,1,1,0,0,0,0,1,560.000000,560.000000,560.000000
3,22000,28.0,0,1,1,0,0,0,0,1,785.714286,0.000000,785.714286
4,18000,30.0,2,1,1,0,0,0,0,1,600.000000,1200.000000,600.000000

In [22]:
df_reduced.to_csv('Data_Reduced.csv', index=False)
print('Reduced data saved to Data_Reduced.csv')

Reduced data saved to Data_Reduced.csv